name: DBT Core Job
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *' # Runs every day at 3 AM

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt
        run: pip install dbt-core

      - name: Run dbt
        run: dbt run
        env:
          DBT_PROFILES_DIR: ${{ secrets.DBT_PROFILES }}
