name: CI Job

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - '!main'

jobs:
  dbt_ci:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_DB: ${{ secrets.SNOWFLAKE_DB }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.17'

      - name: Install requirements
        run: pip install -r requirements.txt  

      - name: Check connection
        run: dbt debug

      - name: Install dbt dependencies
        run: dbt deps

      - name: Run dbt build and generate artifacts
        run: |
          dbt build --target prod --profiles-dir ./
          dbt run --target prod --profiles-dir ./  # You could use `dbt run` here if needed

      - name: Run dbt on modified models with downstream dependencies
        run: |
          dbt build --select state:modified+ --target prod --profiles-dir ./  # Run only modified and downstream models
